DROP TABLE dbo.AspNetUserLogins;
DROP TABLE dbo.AspNetUserRoles;
DROP TABLE dbo.AspNetRoles;
DROP TABLE dbo.AspNetUserClaims;
DROP TABLE dbo.AspNetUsers;
DROP TABLE dbo.Contacts;
DROP TABLE dbo.People;
DROP TABLE dbo.Addresses;
DROP TABLE dbo.__MigrationHistory;
